### NRCAN-Dashboard-Client ****

version: "3.3"
services:
  metnal-wellness-frontend:
    image: metnal-wellness-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      ENV: development
    ports:
      - "3000:3000"
    restart: on-failure
    container_name: metnal-wellness-frontend
