export const MAP_TOPOLOGY_REQUEST = 'overview/MAP_TOPOLOGY_REQUEST';
export const MAP_TOPOLOGY_RESPONSE = 'overview/MAP_TOPOLOGY_RESPONSE';
export const MAP_TOPOLOGY_REQUEST_FAIL = 'overview/MAP_TOPOLOGY_REQUEST_FAIL';